### ISSUE TITLE
"build_danm.sh" does not work out of box

### ISSUE THREAD

**Issue by maxcaresywwforever** [nokia/danm#117] opened 2019-07-30 06:47 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

> Uncomment only one, leave it on its own line:
>
bug
> feature

**What happened**: build_danm.sh report error `can't cd to /go/src/github.com/nokia/danm`
```bash
Executing busybox-1.30.1-r2.trigger
OK: 418 MiB in 34 packages
Removing intermediate container d64597039510
 ---> 55165d816276
Step 7/7 : ENTRYPOINT /build.sh
 ---> Running in ad30f065b0c6
Removing intermediate container ad30f065b0c6
 ---> 7af856ae36ca
Successfully built 7af856ae36ca
Successfully tagged danm_builder:1.0
Running DANM build
+ export 'GOOS=linux'
+ cd /go/src/github.com/nokia/danm
/build.sh: cd: line 3: can't cd to /go/src/github.com/nokia/danm: No such file or directory
build_danm.sh error on line : 12 command was: docker
Terminating with error!
```

**What you expected to happen**: 6 danm binaries generated under `$GOPATH/bin`.

**How to reproduce it**: 
```bash
go get -d github.com/nokia/danm
cd $GOPATH/src/github.com/nokia/danm
./build_danm.sh
```

**Anything else we need to know?**:

**Environment**:
- danm version
`master`, `v4.0.0`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.8", GitCommit:"0c6d31a99f81476dfc9871ba3cf3f597bec29b58", GitTreeState:"clean", BuildDate:"2019-07-08T08:38:54Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- danm configuration:
- OS (e.g. from /etc/os-release):
```
NAME=Fedora
VERSION="29 (Twenty Nine)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Twenty Nine)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
```
- Kernel (e.g. `uname -a`):
```
Linux cdcinfra1-clouddev.dyn.nesc.nokia.net 4.14.114-1.wf30.x86_64 #1 SMP Mon May 6 15:14:16 EEST 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Others:

**Comment by Levovar** [comment] 2019-07-30 16:06
is $GOPATH really set on your host? I suspect not
this is the exact error you get when it is not set, but it totally works for me when it is

**Comment by maxcaresywwforever** [comment] 2019-07-31 01:26
That's right. With `GOPATH` properly configured, it works. But would it more suitable to use `go env GOPATH` to get the `GOPATH` in `scm/build/build.sh` instead of dependent on the environment variable. As far as I know, setting `GOPATH` environment variable is not mandatory step for a go developer.

**Comment by Levovar** [comment] 2019-07-31 04:04
well, when I created the script it kinda was :)

I'm open to contributions as long as the script stays backward compatible, and the builder container picks up the code from the user's workspace in all cases. feel free to create a PR if you have a better way!

I'm gonna close this issue though, considering the script works as intended

**Closed by Levovar** 2019-07-31 04:04 UTC
