### ISSUE TITLE
IPs assigned outside from the IPs allocation pool range

### ISSUE THREAD

**Issue by mardim91** [nokia/danm#182] opened 2020-03-02 13:28 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**: 

> Uncomment only one, leave it on its own line:
>
bug
> feature

**What happened**:
I created a DanmNet and I specifically setted an allocation pool for the IPs. The problem is that the pods that created using that DanmNet got IPs outside of this allocation pool.
**What you expected to happen**:
The Pods should get IPs form the allocation pool range that I specified in DanmNet CR
**How to reproduce it**:
Create a DanmNet with macvlan network type and an allocation pool range. The n spin up two pods and check the IPs of the pods
**Anything else we need to know?**:

**Environment**:
- DANM version (use `danm -version`): v4.1.0-22-gaa3e798
- Kubernetes version (use `kubectl version`):  v1.17.3
- DANM configuration (K8s manifests, kubeconfig files, CNI config file):
- OS (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`): 4.4.0-173-generic
- Others:

**Comment by Levovar** [comment] 2020-03-02 14:31
did you use static, or dynamic allocations?
if static, please note: https://github.com/nokia/danm/issues/128#issuecomment-521213940

**Comment by Levovar** [comment] 2020-03-02 14:45
can confirm, there is a regression on the current master after the recent IPv6 refactorings

**Comment by mardim91** [comment] 2020-03-02 14:59
> did you use static, or dynamic allocations?
> if static, please note: [#128 (comment)](https://github.com/nokia/danm/issues/128#issuecomment-521213940)

I have used dynamic allocation

**Comment by Levovar** [comment] 2020-03-02 15:24
I pushed the correction to https://github.com/nokia/danm/pull/181, feel free to try the branch. added some new UTs for the case, they are passing with it

**Comment by mardim91** [comment] 2020-03-02 15:25
ok thanks I will try it when I will find the time

**Comment by Levovar** [comment] 2020-03-02 17:28
the same root cause resulted in IP allocation logic not loopin over from the beginning of the allocation array once all addresses have been allocated once (but some were freed in the meantime)
that should be also fixed now

**Comment by Levovar** [comment] 2020-03-03 12:46
my tests seem to be passing, so closing the ticket. but if you findany problem feel free to re-open!

**Closed by Levovar** 2020-03-03 12:46 UTC
Labels: bug
