### ISSUE TITLE
Danm doesn't attach SRIOV interface to Pod

### ISSUE THREAD

**Issue by mardim91** [nokia/danm#183] opened 2020-03-03 15:27 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
bug
> feature

**What happened**:
I created the VFs and created also the device_pool through sriov-network-device-plugin. Then I created a sriov danmNet and attached a pod to that sriov danmNet. The problem is that I cannot see the corresponding interface inside the pod. 
**What you expected to happen**:

I expected to see the sriov interface in the pod

**How to reproduce it**:

Below you will find my configuration:

DanmNet:

apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: management
  namespace: example-sriov
spec:
  #Change this to match the CNI config file name in your environment
  NetworkID: flannel
  NetworkType: flannel

apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: sriov-a
  namespace: example-sriov
spec:
  NetworkID: sriov-a
  NetworkType: sriov
  Options:
    #Change this to the name of a valid SR-IOV Device Pool in your cluster
    device_pool: "intel.com/intel_sriov_netdevice"
    container_prefix: first_path
    rt_tables: 250
    #Don't forget to change this to match your switch config!
    cidr: 10.100.20.0/24
    allocation_pool:
      start: 10.100.20.10
      end: 10.100.20.30

kubectl get nodes k8s-master -o json | jq '.status.allocatable'
{
  "cpu": "4",
  "ephemeral-storage": "86310589912",
  "hugepages-2Mi": "0",
  "intel.com/intel_sriov_dpdk": "0",
  "intel.com/intel_sriov_netdevice": "3",
  "intel.com/mlnx_sriov_rdma": "0",
  "memory": "16329888Ki",
  "pods": "110"
}

cat sriov-pod1.yaml: 
apiVersion: v1
kind: Pod
metadata:
  name: sriov-pod1
  namespace: example-sriov
  labels:
    env: test
  annotations:
    danm.k8s.io/interfaces: |
      [
        {"network":"management", "ip":"dynamic"},
        {"network":"sriov-a", "ip":"none"}
      ]
spec:
  containers:
  - name: sriov-pod
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    args:
      - sleep
      - "1000"
    resources:
      requests:
        intel.com/intel_sriov_netdevice: '1'
      limits:
        intel.com/intel_sriov_netdevice: '1'
  nodeSelector:
    sriov: enabled

kubectl exec -it sriov-pod1 -n example-sriov -- env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=sriov-pod1
TERM=xterm
PCIDEVICE_INTEL_COM_INTEL_SRIOV_NETDEVICE=0000:00:0a.0
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_SERVICE_PORT=443
HOME=/root

**Comment by Levovar** [comment] 2020-03-03 15:37
Not sure if your Device Plugin works properly, at least:
PCIDEVICE_INTEL_COM_INTEL_SRIOV_NETDEVICE=0000:00:0a.0
this looks strange for a valid PCI ID

it might be the configuration is wrong, or the DP is old? but IMO the DeviceID should be the PCI ID of the VF

in any case, please share kubelet log, and /var/log/danm.log from around the time this Pod was instantiated

**Comment by mardim91** [comment] 2020-03-03 15:48
@Levovar  I think the PCI ID is ok because I see this on my host :

lspci | grep 0a
00:0a.0 Ethernet controller: Intel Corporation 82599 Ethernet Controller Virtual Function (rev 01)

The logs do not show something usefull but let me share : 

kubelet:

https://pastebin.com/csi8G2kh

danm.log:

https://pastebin.com/vWQ6kkL4

**Comment by Levovar** [comment] 2020-03-03 15:55
are you sure this is from the same node where your SR-IOV test Pod is deployed? I only see CNI_ADD for CoreDNS pods in the DANM log

**Comment by mardim91** [comment] 2020-03-03 15:57
Yes I am pretty sure. I have only one node in my cluster.

**Comment by mardim91** [comment] 2020-03-03 16:06
@Levovar I think danm has stop writting in the danm.log file. I erased and recreated the example-pod but nothing was logged in the danm.log. Strange. Any idea why ?

**Comment by mardim91** [comment] 2020-03-03 16:13
@Levovar I found a related error. Does this ring any bells ?

Mar 03 16:11:23 k8s-master kubelet[17919]: E0303 16:11:23.812845   17919 secret.go:195] Couldn't get secret example-sriov/default-token-xmkk7: failed to sync secret cache: timed out waiting for the condition
Mar 03 16:11:23 k8s-master kubelet[17919]: E0303 16:11:23.812975   17919 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/cde08b24-a73b-4caa-b7ae-a44521ab2644-default-token-xmkk7\" (\"cde08b24-a73b-4caa-b7ae-a44521ab2644\")" failed. No retries permitted until 2020-03-03 16:11:24.312918109 +0000 UTC m=+22.981638526 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"default-token-xmkk7\" (UniqueName: \"kubernetes.io/secret/cde08b24-a73b-4caa-b7ae-a44521ab2644-default-token-xmkk7\") pod \"sriov-pod1\" (UID: \"cde08b24-a73b-4caa-b7ae-a44521ab2644\") : failed to sync secret cache: timed out waiting for the condition

**Comment by mardim91** [comment] 2020-03-03 16:24
ok I found the error here it is:

ERROR: ADD: CNI network could not be set up with error:CNI operation for network:sriov-a failed with:CNI delegation failed due to error:failed to get the name of the sriov PF for device 0000:00:08.0 due to:lstat /sys/bus/pci/devices/0000:00:08.0/physfn/net: no such file or directory

**Comment by mardim91** [comment] 2020-03-03 16:34
@Levovar I checked the path and I dono thave the physfn directory but I do not know why.

sys/bus/pci/devices/0000:00:08.0# ls
broken_parity_status  consistent_dma_mask_bits  dma_mask_bits    enable         local_cpulist  msi_bus   numa_node  rescan    resource0     resource3_wc      subsystem_vendor
class                 d3cold_allowed            driver           firmware_node  local_cpus     msi_irqs  power      reset     resource0_wc  subsystem         uevent
config                device                    driver_override  irq            modalias       net       remove     resource  resource3     subsystem_device  vendor

**Comment by Levovar** [comment] 2020-03-04 09:45
@mardim91 interesting. so, the error is thrown by the SR-IOV CNI actually, not by DANM
maybe you are using an older version of the CNI?
could try upgrading to the release 2.2 https://github.com/intel/sriov-cni/releases

if you are already using this version, that we need to deep-dive into the discovery code. it might be a vendor specific issue as well: what NIC you are using exactly?

**Comment by mardim91** [comment] 2020-03-04 10:16
@Levovar I investigated a bit and I found out that the problem is indeed in SRIOV-CNI. The thing here is that I am running kubernetes in a VM host and not in a baremetal host. So the VFs inside the vm are created first in the baremetal host and then they were passthroughed in the VM so I can use them in pods. That's why it cannot find the PF. The PF doesn't exist in the vm exists only in baremetal. I think a pull request is needed to the sriov cni to address this issue.

**Comment by Levovar** [comment] 2020-03-04 10:29
oh yeah, that is an issue. I will save you one round :)
It is a never ending story if this should work or not. CNI kinda says it shouldn't:
https://github.com/intel/sriov-cni/issues/97

On the DP side it worked for some time, but not anymore:
https://github.com/intel/sriov-network-device-plugin/issues/155#issuecomment-519731987
https://github.com/intel/sriov-network-device-plugin/issues/153#issuecomment-519736560
there are also implicitaions that it only worked because of an unintended side-effect:
https://github.com/intel/sriov-network-device-plugin/issues/208#issuecomment-591242335

but then some other recent threads say it does kinda work?
https://github.com/intel/sriov-network-device-plugin/issues/205

honestly I gave up trying to follow whether it is supported or not, though I also have a use-case like this. maybe could test it with all possible selectors and see if it works with the most recent DP, or not :)
the CNI for sure will fail, but if the DP part works you will still get the PCI device mounted into your container (you just need to add network config on top of it yourself, such as IP / IP routes /VLAN etc.)

alternative would be using the host-device CNI to handle PFs

**Comment by Levovar** [comment] 2020-03-05 10:05
considering the issue is not with DANM I'm closing it, but as always, feel free to re-open if you still have any questions

**Comment by mardim91** [comment] 2020-03-05 10:06
Yes ok thanks!

**Closed by Levovar** 2020-03-05 10:05 UTC
Labels: support
