### ISSUE TITLE
Fail to build webhook image in v4.0.0 release

### ISSUE THREAD

**Issue by maxcaresywwforever** [nokia/danm#124] opened 2019-08-09 08:20 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
bug
> feature

**What happened**:  Fail to generate `webhook` docker image .

```
Step 9/10 : RUN apk add --no-cache --virtual .tools ca-certificates gcc musl-dev go glide git tar curl && mkdir -p $GOPATH/src/github.com/nokia/danm && git clone -b 'webhook' --depth 1 https://github.com/nokia/danm.git $GOPATH/src/github.com/nokia/danm && cd $GOPATH/src/github.com/nokia/danm && glide install --strip-vendor && go get -d github.com/vishvananda/netlink && go get github.com/containernetworking/plugins/pkg/ns && go get github.com/golang/groupcache/lru && rm -rf $GOPATH/src/k8s.io/code-generator && git clone -b 'kubernetes-1.13.4' --depth 1 https://github.com/kubernetes/code-generator.git $GOPATH/src/k8s.io/code-generator && go install k8s.io/code-generator/cmd/deepcopy-gen && go install k8s.io/code-generator/cmd/client-gen && go install k8s.io/code-generator/cmd/lister-gen && go install k8s.io/code-generator/cmd/informer-gen && deepcopy-gen --alsologtostderr --input-dirs github.com/nokia/danm/crd/apis/danm/v1 -O zz_generated.deepcopy --bounding-dirs github.com/nokia/danm/crd/apis && client-gen --alsologtostderr --clientset-name versioned --input-base "" --input github.com/nokia/danm/crd/apis/danm/v1 --clientset-path github.com/nokia/danm/crd/client/clientset && lister-gen --alsologtostderr --input-dirs github.com/nokia/danm/crd/apis/danm/v1 --output-package github.com/nokia/danm/crd/client/listers && informer-gen --alsologtostderr --input-dirs github.com/nokia/danm/crd/apis/danm/v1 --versioned-clientset-package github.com/nokia/danm/crd/client/clientset/versioned --listers-package github.com/nokia/danm/crd/client/listers --output-package github.com/nokia/danm/crd/client/informers && go install -a -ldflags '-extldflags "-static"' github.com/nokia/danm/cmd/webhook && cp $GOPATH/bin/webhook /usr/local/bin/webhook && rm -rf $GOPATH/src && rm -rf $GOPATH/bin && apk del .tools && rm -rf /var/cache/apk/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/* && rm -rf ~/.glide
 ---> Running in 8be13f8d2b8b
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/25) Upgrading musl (1.1.20-r4 -> 1.1.20-r5)
(2/25) Installing ca-certificates (20190108-r0)
(3/25) Installing binutils (2.31.1-r2)
(4/25) Installing gmp (6.1.2-r1)
(5/25) Installing isl (0.18-r0)
(6/25) Installing libgomp (8.3.0-r0)
(7/25) Installing libatomic (8.3.0-r0)
(8/25) Installing libgcc (8.3.0-r0)
(9/25) Installing mpfr3 (3.1.5-r1)
(10/25) Installing mpc1 (1.0.3-r1)
(11/25) Installing libstdc++ (8.3.0-r0)
(12/25) Installing gcc (8.3.0-r0)
(13/25) Installing musl-dev (1.1.20-r5)
(14/25) Installing go (1.11.5-r0)
(15/25) Installing glide (0.13.2-r0)
(16/25) Installing nghttp2-libs (1.35.1-r0)
(17/25) Installing libssh2 (1.8.2-r0)
(18/25) Installing libcurl (7.64.0-r2)
(19/25) Installing expat (2.2.7-r0)
(20/25) Installing pcre2 (10.32-r1)
(21/25) Installing git (2.20.1-r0)
(22/25) Installing tar (1.32-r0)
(23/25) Installing curl (7.64.0-r2)
(24/25) Installing .tools (0)
(25/25) Upgrading musl-utils (1.1.20-r4 -> 1.1.20-r5)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 383 MiB in 39 packages
Cloning into '/go/src/github.com/nokia/danm'...
warning: Could not find remote branch webhook to clone.
fatal: Remote branch webhook not found in upstream origin
```

**What you expected to happen**: `webhook` docker image is generated successfully using `webhook` dockerfile

**How to reproduce it**:
`docker build -t webhook:latest integration/docker/webhook`

**Anything else we need to know?**:

Error happens in command `git clone -b 'webhook' --depth 1 https://github.com/nokia/danm.git $GOPATH/src/github.com/nokia/danm `. Trying to clone `webhook` branch but it is not exist.

**Environment**:
- danm version
- Kubernetes version (use `kubectl version`):
- danm configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Fillamug** [comment] 2019-08-09 12:11
Hello! This has already been fixed in the master branch, so use the dockerfile from there.

**Comment by Levovar** [comment] 2019-08-09 13:33
yep, it should build from master!

fixed in https://github.com/nokia/danm/commit/1ab952ba90b263cf5e4e5fd4fda4930e433d4eca

**Comment by maxcaresywwforever** [comment] 2019-08-09 23:15
@Fillamug @Levovar 
But that means v4.0.0 is not a working release out of box.  Users will not choose `master` branch if for product usage. Instead, a well-tested and stable release is always preferred.

**Comment by Levovar** [comment] 2019-08-12 06:28
it is an entirely working release, out of the box
the integration files are for your reference on which based you can easily integrate it into your product. nowhere it is stated that you _should_ take those files as-is. in fact, in almost all cases they need environment specific alignment

BTW I myself integrate from upstream based on commit hashes, not from releases :)
in any case, that is the price you pay for using an upstream component in a production environment. integration and support is kind fo your job. I'm happy to assist of course as much as possible, but we don't have a contract, SLAs, guarantees etc.
release branches are not gonna be supported. this is strictly a master-only project

**Comment by Levovar** [comment] 2019-08-12 06:33
if you prefer releases, 4.1 is planned to be released around September.
but as with all open-source projects, integrated from commit hashes or releases: I highly suggest to you to create some kind of acceptance test suite within your product. we test the releases as much as possible, but as with all things, it is best effort
the CI does not currently include functional testing, only UT

in any case, the issue is solved as per the linked commit message. hope you appreciate the background information too :)

**Closed by Levovar** 2019-08-12 06:33 UTC

**Comment by maxcaresywwforever** [comment] 2019-08-12 06:42
> this is strictly a master-only project

If this is the case, I will switch to master branch for integration.

**Comment by Levovar** [comment] 2019-08-12 06:49
> If this is the case, I will switch to master branch for integration.

just ot be clear on what that means: master is also not guaranteed to be perfect all the time, despite best efforts (it should be good right now)
but  all corrections to raised issues are only pushed to master, and only released with subsequent releases

so yes, it is always the pan to only release tested releases. yes, it is always the plan to provide bug free software. it is always the plan to keep master in continuous tip-top shape
but it is all best effort, and should be treated as such

**Comment by maxcaresywwforever** [comment] 2019-08-13 04:12
Understood. I was trying to markdown the issues i faced during my integration, nothing else. I probably will keep integration with the master branch, and contribute back to the project with feedback or code contributions. Overall, i pretty much would like to see `danm` becoming great and popular kubernetes network solution in the container industry.
