### ISSUE TITLE
Defining default networks example

### ISSUE THREAD

**Issue by belvarr** [nokia/danm#154] opened 2019-09-26 09:02 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

feature

**What happened**:
I try to define default network with no luck in lightweight environment 
  
**What you expected to happen**:
My cluster is up and running with flannel as default network while i will defined my won DanmNet networks in annotations 

**How to reproduce it**:
an example yml file to create the default network

**Environment**:
- danm version:v4.0 from master branch
- Kubernetes version (use `kubectl version`): v1.15.3
- danm configuration: as doc and example no special configuration
- OS (e.g. from /etc/os-release):Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`):4.15.0-64-generic

**Comment by Levovar** [comment] 2019-09-26 10:31
default network is only read if you don't define your network connections.
when you are "DANM aware" and would like to explicitly define your network connections, define them all :)

**Comment by belvarr** [comment] 2019-10-01 10:32
@Levovar Thanks for your reply

I have created two default network on in kube-system namespace and another one in default namespace cause the coredns pod and dashboard pods were crashed so that i have to rest the cluster first then create the mentioned default networks.

Also i face bug when create danm network as in step 8 of Deployment section 

kubectl create -f  integration/bootstrap_networks/lightweight/flannel.yaml

As I edit NetworkID from flannel to 10-flannel cause this is my flannel file name in /etc/cni/net.d/

ls -l /etc/cni/net.d/10-flannel*
-rw-r--r-- 1 root root 313 Oct  1 12:22 10-flannel.conflist

but after that webhook deployment get failed as it expect the file name 10-flannel.conf not 10-flannel.conflist 

i was trying to rename file from flannel side with no luck which get other dns service to fail so please any help for this issue from your side.

**Comment by Levovar** [comment] 2019-10-01 16:04
> I have created two default network one in kube-system namespace 
wow, how? :)

> but after that webhook deployment get failed as it expect the file name 10-flannel.conf not 10-flannel.conflist
correct

> i was trying to rename file from flannel side with no luck which get kubernetes pod dns to fail so please any help for this issue from your side.
and that is because we don't support chaining together multiple CNI invocations into one call. I suspect your Flannel config is like that (flannel + portmap)
can you share how it looks like?

**Comment by belvarr** [comment] 2019-10-01 17:42
I appreciate your support it seams that is correct i notice that flannel config is as you said (flannel + portmap)

this is deployed yaml file

```
# cat /etc/kubernetes/cni-flannel.yml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: "kube-system"
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name":"cni0",
      "cniVersion":"0.3.1",
      "plugins":[
        {
          "type":"flannel",
          "delegate":{
            "forceAddress":true,
            "hairpinMode": true,
            "isDefaultGateway":true
          }
        },
        {
          "type":"portmap",
          "capabilities":{
            "portMappings":true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.233.64.0/18",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel
  namespace: "kube-system"
  labels:
    tier: node
    k8s-app: flannel
spec:
  selector:
    matchLabels:
      tier: node
      k8s-app: flannel
  template:
    metadata:
      labels:
        tier: node
        k8s-app: flannel
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: flannel
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.11.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 300m
            memory: 500M
          requests:
            cpu: 150m
            memory: 64M
        command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr" ]
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: run
          mountPath: /run
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      - name: install-cni
        image: quay.io/coreos/flannel-cni:v0.3.0
        command: ["/install-cni.sh"]
        env:
        # The CNI network config to install on each node.
        - name: CNI_NETWORK_CONFIG
          valueFrom:
            configMapKeyRef:
              name: kube-flannel-cfg
              key: cni-conf.json
        - name: CNI_CONF_NAME
          value: "10-flannel.conflist"
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: host-cni-bin
          mountPath: /host/opt/cni/bin/
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: Exists
        # Mark pod as critical for rescheduling (Will have no effect starting with kubernetes 1.12)
        - key: CriticalAddonsOnly
          operator: "Exists"
      volumes:
        - name: run
          hostPath:
            path: /run
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: flannel-cfg
          configMap:
            name: kube-flannel-cfg
        - name: host-cni-bin
          hostPath:
            path: /opt/cni/bin
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 20%
    type: RollingUpdate

```

**Comment by Levovar** [comment] 2019-10-02 08:55
just use a standard CNI config without the plugin section, and you are gonna be okay :)
like this:
[cloudadmin@controller-1 ~]$ cat /etc/cni/net.d/flannel.conf
{
  "name": "cbr0",
  "type": "flannel",
  "cniVersion": "0.3.1",
  "delegate": {
    "hairpinMode": true,
    "isDefaultGateway": true
  }
}

**Comment by belvarr** [comment] 2019-10-03 08:42
@Levovar  Thanks a lot it works.
can I ask you about function of portmap as i cannot find it on flannel doc :(.

**Comment by Levovar** [comment] 2019-10-03 09:47
asking the million dollar question :D TBH I have no idea. I personally never thought to use it
I guess it can be used when you want to expose your overlay IP, but I never understood why wouldn't you simply use Kubernetes Services for that (externalIP, nodePort etc.)

**Comment by Levovar** [comment] 2019-10-11 09:39
closing as I guess the issue is solved, but feel free to re-open in case something is still not okay!

**Closed by Levovar** 2019-10-11 09:39 UTC
Labels: support
