### ISSUE TITLE
Tenant network always loss ipvlan link 

### ISSUE THREAD

**Issue by antzjm** [nokia/danm#257] opened 2021-06-03 07:46 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> bug

**What happened**:
After I restart host infra, The tenant network with ipvlan always loss links. And I restart network-watch daemon-set to recover.
**What you expected to happen**:
Restart host and keep fine.
**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- DANM version (use `4.1.0-2`):
- Kubernetes version (use `v1.16.2`):
- DANM configuration (K8s manifests, kubeconfig files, CNI config file):
- tenant.yaml
- apiVersion: danm.k8s.io/v1
kind: TenantNetwork
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"danm.k8s.io/v1","kind":"TenantNetwork","metadata":{"annotations":{},"name":"internal","namespace":"cran1"},"spec":{"NetworkID":"internal","NetworkType":"ipvlan","Options":{"allocation_pool":{"end":"192.168.1.254","start":"192.168.1.2"},"cidr":"192.168.1.0/24","container_prefix":"internal","host_device":"ens1f1"}}}
  creationTimestamp: "2021-03-31T05:50:44Z"
  generation: 3932
  name: internal
  namespace: cran1
  resourceVersion: "18383421"
  selfLink: /apis/danm.k8s.io/v1/namespaces/cran1/tenantnetworks/internal
  uid: df1526ba-95c6-45c1-a8a1-a214f9306ae9
spec:
  NetworkID: internal
  NetworkType: ipvlan
  Options:
    alloc: vIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE=
    allocation_pool:
      end: 192.168.1.254
      start: 192.168.1.2
    cidr: 192.168.1.0/24
    container_prefix: internal
    host_device: ens1f1
    vlan: 1711

- 
- OS (e.g. from /etc/os-release): CentOS Linux release 7.8.2003 (Core)
- Kernel (e.g. `uname -a`): Linux controller-1 4.19.162-1.el7.centos.ncir.x86_64 
- Others:

**Comment by Levovar** [comment] 2021-06-09 13:01
@antzjm : you to check if I understand the problem description
1: you deploy above network -> netwatcher creates the host interface as usual
2: you restart the host -> host VLAN interface disappears
3: you restart netwatcher on this host -> host VLAN interface is re-created again
is this correct?

**Comment by antzjm** [comment] 2021-06-10 06:04
@Levovar Yes. When host VLAN interface loss, pod can not created due to CNI network plugin fail.

**Comment by Levovar** [comment] 2021-06-23 15:01
`# ip l | grep 2000
# kubectl create -f test_net.yaml
clusternetwork.danm.k8s.io/external created
# ip l | grep 2000
117: external.2000@infra-bond: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default
# reboot
...
# ip l | grep 2000
91: external.2000@infra-bond: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default
`

I'm not sure what's you rissue exactly, but the described scenario works as intended

**Comment by Levovar** [comment] 2021-07-02 15:15
closing as the reported scenario cannot be reproduced, and is working as intended

**Closed by Levovar** 2021-07-02 15:15 UTC
